Update feature tests for add / edit timeline entry
alphagov/collections-publisher pull request #1255
Opened 2021-01-22 11:40 UTC by leenagupte

Trello: https://trello.com/c/W4nJDLBi

# What's changed and why?
When the add and edit timeline pages where created, the timeline section
hadn't been added to the summary page. Now that the timeline section
exists, the feature tests can be updated to properly represent the user
journey / experience.

⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

2021-01-22 17:08 UTC, Rosa-Fox requested changes
Looks good... one teeny comment!

2021-01-22 17:08 UTC, Rosa-Fox commented on spec/support/coronavirus_feature_steps.rb
> +def add_i_add_a_new_timeline_entry
`and_i_add_a_new_timeline_entry` rather than `add_i_add`

2021-01-22 17:11 UTC, leenagupte commented on spec/support/coronavirus_feature_steps.rb
> +def add_i_add_a_new_timeline_entry
Oops! Good spot.

2021-01-22 17:35 UTC, leenagupte commented
@Rosa-Fox Thanks for your review. I've updated the test and fixed up.

2021-01-27 15:52 UTC, Rosa-Fox approved these changes

2021-01-27 17:43 UTC, merged