Drop the tag_associations table 3/4
alphagov/collections-publisher pull request #2111
Opened 2024-03-18 08:14 UTC by georges1996

⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

Once we have removed all the associated code to the tag_associations table, we can now drop the table. Note I have done this in a way where we can roll back the migration in case anything goes wrong, in order to regenerate the table structure. 

https://trello.com/c/RLc9saF6/2461-remove-specialist-topic-code-from-collections-publisher-m-l

2024-03-20 15:26 UTC, unoduetre requested changes

2024-03-20 15:26 UTC, unoduetre commented on db/migrate/20240318080818_drop_associations_table.rb
> +    drop_table :tag_associations do |t|
Might be useful to drop index separately in case one wants to reverse this migration.

2024-03-20 16:58 UTC, beccapearce approved these changes

2024-03-21 09:05 UTC, unoduetre commented on db/migrate/20240318080818_drop_associations_table.rb
> +    drop_table :tag_associations do |t|
Yes, you can reverse it, but the result won't be the same. You can compare the schema before and after reversing.

2024-03-21 09:21 UTC, unoduetre commented on db/migrate/20240318080818_drop_associations_table.rb
> +    drop_table :tag_associations do |t|
I've confirmed that is not the case, so it needs to be added.

2024-03-21 14:40 UTC, unoduetre approved these changes
Approved.

2024-03-26 11:46 UTC, anatron approved these changes
LGTM!

2024-04-03 09:08 UTC, merged